# Generated by Django 5.2.14 on 2026-05-16 14:55

import datetime
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('paragraph', 0), ('heading', 1), ('image', 2)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
            ],
            options={
                'verbose_name': 'About Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Blog',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_badge_text', models.CharField(blank=True, max_length=200)),
                ('hero_heading', models.CharField(default='Your digital identity, one tap away', max_length=300)),
                ('hero_subtext', models.TextField(blank=True)),
                ('hero_primary_cta_label', models.CharField(default="Create your card — it's free", max_length=100)),
                ('hero_secondary_cta_label', models.CharField(default='See how it works →', max_length=100)),
                ('hero_social_proof_text', models.CharField(blank=True, default='12,000+ professionals already use VCard', max_length=200)),
                ('features', wagtail.fields.StreamField([('feature', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Emoji or single character icon', 'max_length': 10}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('description', 2)]], {})})),
                ('steps', wagtail.fields.StreamField([('step', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {})})),
                ('testimonials', wagtail.fields.StreamField([('testimonial', 3)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('quote', 0), ('author_name', 1), ('author_role', 1), ('avatar', 2)]], {})})),
                ('cta_heading', models.CharField(blank=True, default='Ready to make your mark?', max_length=200)),
                ('cta_subtext', models.CharField(blank=True, default="Join 12,000+ professionals who've gone digital. Free to start, no credit card required.", max_length=300)),
                ('cta_button_label', models.CharField(default='Start your free card →', max_length=100)),
            ],
            options={
                'verbose_name': 'Home Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Legal Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PricingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', models.CharField(default='Simple, transparent pricing', max_length=200)),
                ('subtext', models.CharField(blank=True, default="Start free. Upgrade when you're ready.", max_length=400)),
                ('tiers', wagtail.fields.StreamField([('tier', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. $9.99', 'max_length': 20}), 2: ('wagtail.blocks.CharBlock', (), {'default': '/mo', 'max_length': 20}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('name', 0), ('price', 1), ('period', 2), ('description', 3), ('features', 4), ('is_popular', 5), ('cta_label', 0), ('cta_url', 3)]], {})})),
                ('faq', wagtail.fields.StreamField([('faq', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 300}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {})})),
            ],
            options={
                'verbose_name': 'Pricing Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('author', models.CharField(max_length=200)),
                ('published_date', models.DateField(default=datetime.date.today)),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('body', wagtail.fields.StreamField([('paragraph', 0), ('heading', 1), ('image', 2)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Blog Post',
            },
            bases=('wagtailcore.page',),
        ),
    ]
