# Generated by Django 5.1.4 on 2025-06-20 22:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_type', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business'), ('freelance', 'Freelance'), ('academic', 'Academic'), ('creative', 'Creative')], default='personal', max_length=20)),
                ('custom_url', models.SlugField(blank=True, help_text='Custom URL path (leave blank for auto-generation)', unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True, help_text='Short bio or description', max_length=500)),
                ('skills', models.TextField(blank=True, help_text='Skills or services offered')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('custom_link_1_title', models.CharField(blank=True, max_length=50)),
                ('custom_link_1_url', models.URLField(blank=True)),
                ('custom_link_2_title', models.CharField(blank=True, max_length=50)),
                ('custom_link_2_url', models.URLField(blank=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Card',
                'verbose_name_plural': 'Business Cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='cards.businesscard')),
            ],
            options={
                'verbose_name': 'Card View',
                'verbose_name_plural': 'Card Views',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ContactDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('download_type', models.CharField(choices=[('vcard', 'vCard Download'), ('contact', 'Add to Contacts')], default='vcard', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='cards.businesscard')),
            ],
            options={
                'verbose_name': 'Contact Download',
                'verbose_name_plural': 'Contact Downloads',
                'ordering': ['-timestamp'],
            },
        ),
    ]
