# Generated by Django 5.1.4 on 2025-12-28 21:26

import cards.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_countrycode_businesscard_accent_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='accent_color',
            field=models.CharField(default='#764ba2', help_text='Background gradient end color (hex format: #764ba2)', max_length=7, validators=[cards.models.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='background_color',
            field=models.CharField(default='#667eea', help_text='Background gradient start color (hex format: #667eea)', max_length=7, validators=[cards.models.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='phone',
            field=models.CharField(blank=True, help_text='Include country code (e.g., +965 12345678)', max_length=20, validators=[cards.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='text_color',
            field=models.CharField(default='#ffffff', help_text='Text color for hero section (hex format: #ffffff)', max_length=7, validators=[cards.models.validate_hex_color]),
        ),
    ]
