# Generated by Django 5.1.4 on 2026-01-03 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_businesscard_owner_alter_businesscard_accent_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscard',
            name='owner',
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='accent_color',
            field=models.CharField(default='#764ba2', help_text='Background gradient end color (hex format: #764ba2)', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color code')]),
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='background_color',
            field=models.CharField(default='#667eea', help_text='Background gradient start color (hex format: #667eea)', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color code')]),
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='text_color',
            field=models.CharField(default='#ffffff', help_text='Text color for hero section (hex format: #ffffff)', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color code')]),
        ),
    ]
