# Generated by Django 5.1.4 on 2026-02-26 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_businesscard_owner_alter_businesscard_accent_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('email_click', 'Email Click'), ('phone_click', 'Phone Click'), ('whatsapp_click', 'WhatsApp Click'), ('website_click', 'Website Click'), ('vcard_download', 'vCard Download'), ('social_linkedin', 'LinkedIn'), ('social_twitter', 'Twitter/X'), ('social_instagram', 'Instagram'), ('social_facebook', 'Facebook'), ('social_portfolio', 'Portfolio'), ('custom_link', 'Custom Link')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='cards.businesscard')),
            ],
            options={
                'verbose_name': 'Card Interaction',
                'verbose_name_plural': 'Card Interactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
