# Generated by Django 5.1.4 on 2026-02-26 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_backfill_organizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField(max_length=1000)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='cards.businesscard')),
            ],
            options={
                'verbose_name': 'Card Lead',
                'verbose_name_plural': 'Card Leads',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
